### ISSUE TITLE
[ 프로젝트 피드백 2 ]

### ISSUE THREAD

**Issue by thesun4sky** [LeeChangHyeong/OwnCalendar#2]
안녕하세요 창형님~! 

리프레쉬 토큰은 어렵다보니까 패스하신것 같지만 일정&댓글 수정 까지 잘 구현해주셨습니다.
commit 룰을 잘 지켜서 작성해주셔서 구현 기능들을 둘러보는데 큰 도움이 되었습니다.
이부분은 협업하실때나 버그 트래킹 할때에도 큰 도움이 될거니까 잘 지켜나가시면 좋을 것 같습니다.
다만 일부 커밋에서 커밋메세지가 중복되는게 있었는데 이런것들은 변경사항을 합쳐주는 amend commit 이란걸 활용해보세요.
토큰을 잘 저장하고 권한도 넣고 토큰으로 인증하는것까지 구현해주신것 잘 확인 했습니다.

고생하셨습니다.

**Comment by LeeChangHyeong** [comment]
amend commit 잘 활용해 보겠습니다! 피드백 감사합니다🙇🏻‍♂️
